
""" ESTE ARCHIVO GUARDA LAS CONSTANTES UTILIZADAS EN TODA LA APP, SE INVOCAN POR EL NOMBRE """

LOGIN_CREDENCIAL_INVALIDA = 'EL USUARIO O EL PASSWORD SON INCORRECTOS. INTENTE NUEVAMENTE'
LOGOUT = 'A CERRADO SESION EXITOSAMENTE!'
MENSAJE_BIENVENIDA = 'BIENVENIDO(A) A TU TIENDA DE PELICULAS!'